env:
  TERM: xterm-256color

window:
  padding:
    x: 4
    y: 4
  opacity: 0.95

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

font:
  size: 14
  normal:
    family: "FiraMono Nerd Font"
  bold:
    family: "FiraMono Nerd Font"
  italic:
    family: "FiraMono Nerd Font"
  bold_italic:
    family: "FiraMono Nerd Font"

cursor:
  unfocused_hollow: true

# Enable ligatures if your font supports them
draw_bold_text_with_bright_colors: true  # Enable bright color support
use_thin_strokes: true  # Enable thin strokes for bold text
font_features:
  - "calt"  # Contextual Alternates (ligatures)
  - "liga"  # Standard Ligatures
  - "clig"  # Contextual Ligatures

# Colors (Cobalt2)
colors:
  # Default colors
  primary:
    background: '0x122738'
    foreground: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x20fa7b'
    yellow:  '0xffc600'
    blue:    '0xcaa9fa'
    magenta: '0xff68B8'
    cyan:    '0x8be9fd'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x666575'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'
