
start-at-login = true

after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]


[gaps]
    inner.horizontal = 8
    inner.vertical = 8
    outer.left = 12
    outer.bottom = 12
    outer.top =  [{monitor.'^built-in retina display$' = 10 }, 40]
    outer.right = 12

[mode.main.binding]
    alt-tab = 'workspace-back-and-forth'
    alt-shift-semicolon = [
        'mode service',
        'exec-and-forget sketchybar --trigger send_mode MESSAGE="SERVICE" HOLD="true"'
    ]

    ctrl-space = [
        'mode alt',
        'exec-and-forget sketchybar --trigger send_mode MESSAGE="ALT" HOLD="true"'
    ]

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-p = 'workspace P'
    alt-s = 'workspace S'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 4'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-p = 'move-node-to-workspace P'
    alt-shift-s = 'move-node-to-workspace S'


    alt-o = 'workspace prev'
    alt-i = 'workspace next'

    ctrl-alt-h = 'focus left'
    ctrl-alt-j = 'focus down'
    ctrl-alt-k = 'focus up'
    ctrl-alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

[mode.alt.binding]
    esc = [
    'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
]
    space = [
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ]

    ctrl-space = [
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ]

    r = [
        'reload-config',
        'exec-and-forget sketchybar --trigger hide_mode',
        'exec-and-forget sketchybar --reload',
        'mode main',
    ]
    
    slash = 'layout tiles horizontal vertical'
    comma = 'layout accordion horizontal vertical'


    h = 'focus left'
    j = 'focus down'
    k = 'focus up'
    l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    shift-h = 'move left'
    shift-j = 'move down'
    shift-k = 'move up'
    shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    minus = 'resize smart -64'
    equal = 'resize smart +64'
    shift-minus = 'resize smart -128'
    shift-equal = 'resize smart +128'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    o = 'workspace prev'
    i = 'workspace next'

    shift-u = 'move-node-to-workspace prev'
    shift-i = 'move-node-to-workspace next'

    1 = 'workspace 1' # Terminal
    2 = 'workspace 2' # Browser
    3 = 'workspace 3' # Database
    4 = 'workspace 4' # Utils
    5 = 'workspace 5' # ChatGPT
    p = 'workspace P' # Personal
    s = 'workspace S' # Chat

    shift-1 = 'move-node-to-workspace 1'
    shift-2 = 'move-node-to-workspace 2'
    shift-3 = 'move-node-to-workspace 3'
    shift-4 = 'move-node-to-workspace 4'
    shift-5 = 'move-node-to-workspace 5'
    shift-p = 'move-node-to-workspace P'
    shift-s = 'move-node-to-workspace S'

    tab = 'workspace-back-and-forth'
    semicolon = [
        'mode spacial',
        'exec-and-forget sketchybar --trigger send_mode MESSAGE="SERVICE" HOLD="true"'
    ]
  
# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = [
    'mode main',
    'exec-and-forget sketchybar --trigger hide_mode'
    ]
    space = [
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ]
    0 = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = [
        'layout floating tiling',
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

# Float the Google Meet PIP
[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    if.window-title-regex-substring = '^about:blank - (?!Google Chrome).*$'
    run = ['layout floating']

# this may not be needed
[[on-window-detected]]
    if.app-id = 'com.dottt.app'
    run = ['layout floating']

# move wezterm to W when it opens
[[on-window-detected]]
    if.app-id = 'com.github.wez.terminal'
    run = 'move-node-to-workspace W'


## TODO - Set remaining on-window-detected events for other spaces
