
start-at-login = true

after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]


[gaps]
    inner.horizontal = 8
    inner.vertical = 8
    outer.left = 12
    outer.bottom = 12
    outer.top =  [{monitor.'^built-in retina display$' = 10 }, 40]
    outer.right = 12

[mode.main.binding]
    alt-tab = 'workspace-back-and-forth'

    ctrl-space = [
        'mode alt',
        'exec-and-forget sketchybar --trigger send_mode MESSAGE="AERO" HOLD="true"'
    ]

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-p = 'workspace P'
    alt-s = 'workspace S'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-p = 'move-node-to-workspace P'
    alt-shift-s = 'move-node-to-workspace S'

    alt-i = 'workspace prev'
    alt-o = 'workspace next'

    alt-enter = 'fullscreen'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-ctrl-h = 'move left'
    alt-ctrl-j = 'move down'
    alt-ctrl-k = 'move up'
    alt-ctrl-l = 'move right'

    alt-shift-h = 'join-with left'
    alt-shift-j = 'join-with down'
    alt-shift-k = 'join-with up'
    alt-shift-l = 'join-with right'

    alt-minus = 'resize smart -64'
    alt-equal = 'resize smart +64'
    alt-shift-minus = 'resize smart -128'
    alt-shift-equal = 'resize smart +128'

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

[mode.alt.binding]
    esc = [
    'mode main',
    'exec-and-forget sketchybar --trigger hide_mode'
   ]

    space = [
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ]


    0 = [
        'flatten-workspace-tree',
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ] # reset layout

    f = [
        'layout floating tiling',
        'mode main',
        'exec-and-forget sketchybar --trigger hide_mode'
    ] # Toggle between floating and tiling layout

    r = [
        'reload-config',
        'exec-and-forget sketchybar --trigger hide_mode',
        'exec-and-forget sketchybar --reload',
        'mode main',
    ]
    
    shift-h = ['join-with left']
    shift-j = ['join-with down']
    shift-k = ['join-with up']
    shift-l = ['join-with right']

    alt-shift-h = 'focus left'
    alt-shift-j = 'focus down'
    alt-shift-k = 'focus up'
    alt-shift-l = 'focus right'

    alt-ctrl-h = 'move left'
    alt-ctrl-j = 'move down'
    alt-ctrl-k = 'move up'
    alt-ctrl-l = 'move right'
  
# Float the Google Meet PIP
[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    if.window-title-regex-substring = '^about:blank - (?!Google Chrome).*$'
    run = ['layout floating']

# this may not be needed
[[on-window-detected]]
    if.app-id = 'com.dottt.app'
    run = ['layout floating']

# move wezterm to W when it opens
[[on-window-detected]]
    if.app-id = 'com.github.wez.terminal'
    run = 'move-node-to-workspace W'


## TODO - Set remaining on-window-detected events for other spaces
