local colors = require('grapelean.utils').colors
local Group = require('grapelean.utils').Group

Group.new('NotifyDEBUGBorder', colors.pink, nil, nil)
Group.new('NotifyBackground', nil, colors.bg, nil)
Group.new('NotifyDEBUGIcon', colors.pink, nil, nil)
Group.new('NotifyDEBUGTitle', colors.pink, nil, nil)
Group.new('NotifyERRORBorder', colors.red:light(), nil, nil)
Group.new('NotifyERRORIcon', colors.red:light(), nil, nil)
Group.new('NotifyERRORTitle', colors.red:light(), nil, nil)
Group.new('NotifyINFOBorder', colors.blue_light, nil, nil)
Group.new('NotifyINFOIcon', colors.blue_light, nil, nil)
Group.new('NotifyINFOTitle', colors.blue_light, nil, nil)
Group.new('NotifyTRACEBorder', colors.green, nil, nil)
Group.new('NotifyTRACEIcon', colors.green, nil, nil)
Group.new('NotifyTRACETitle', colors.green, nil, nil)
Group.new('NotifyWARNBorder', colors.yellow_light, nil, nil)
Group.new('NotifyWARNIcon', colors.yellow_light, nil, nil)
Group.new('NotifyWARNTitle', colors.yellow_light, nil, nil)
