local colors = require("grapelean.utils").colors
local Group = require("grapelean.utils").Group

Group.new("NvimTreeEmptyFolderName", colors.red_dark, nil, nil)
Group.new("NvimTreeFolderIcon", colors.yellow, nil, nil)
Group.new("NvimTreeFolderName", colors.blue, nil, nil)
Group.new("NvimTreeGitDeleted", colors.red, nil, nil)
Group.new("NvimTreeGitDirty", colors.green_muted, nil, nil)
Group.new("NvimTreeGitNew", colors.green, nil, nil)
Group.new("NvimTreeImageFile", colors.pink, nil, nil)
Group.new("NvimTreeIndentMarker", colors.gray_light, nil, nil)
Group.new("NvimTreeNormal", colors.white, nil, nil)
Group.new("NvimTreeOpenedFile", colors.yellow, nil, nil)
Group.new("NvimTreeOpenedFolderName", colors.pink, nil, nil)
Group.new("NvimTreeRootFolder", colors.yellow, nil, nil)
Group.new("NvimTreeSpecialFile", colors.blue_light, nil, nil)
Group.new("NvimTreeStatuslineNc", colors.gray_light, nil, nil)
Group.new("NvimTreeSymlink", colors.pink_light, nil, nil)
Group.new("NvimTreeVertSplit", colors.gray_light, nil, nil)
