local hl     = require('grapelean.utils').hl
local pal    = require 'grapelean.palette'
local p      = pal.palette
local s      = pal.semantic
local darken = require('grapelean.color').darken

hl('GitSignsAdd',               { fg = s.added })
hl('GitSignsChange',            { fg = s.modified })
hl('GitSignsCurrentLineBlame',  { fg = darken(p.gray_light) })
hl('GitSignsDelete',            { fg = s.removed })
hl('GitSignsDeletePreview',     { fg = s.removed })
hl('GitSignsDeleteVirtLn',      { fg = p.pink })
hl('GitSignsAddPreview',        { fg = s.added })
hl('GitSignsUntracked',         { fg = s.added })
hl('GitSignsUntrackedLn',       { fg = s.added })
hl('GitSignsUntrackedNr',       { fg = s.added })
hl('GitSignsAddInline',         { fg = s.added })
hl('GitSignsAddLnInline',       { fg = s.added })
hl('GitSignsDeleteInline',      { fg = p.pink })
hl('GitSignsDeleteLnInline',    { fg = p.pink })
hl('GitSignsDeleteVirtLnInline',{ fg = p.pink })
hl('GitSignsChangeInline',      { fg = s.modified })
hl('GitSignsChangeLnInline',    { fg = s.modified })
