#!/bin/bash

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Aerospace, helps display Mission Control windows correctly https://nikitabobko.github.io/AeroSpace/guide#emulation-of-virtual-workspaces
defaults write com.apple.dock expose-group-apps -bool true && killall Dock
