local icons = {
  code = '',
  diagnostics = '',
  file = '',
  git = '󰊢',
  image = '',
  note = '',
  search = '',
  test = '󰱑',
  text = '󰊄',
  toggle = '',
}

return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>i', desc = 'Paste image from clipboard', icon = { icon = icons.image, color = 'blue' } },
      { '<leader>p', desc = 'Paste from system clipboard', icon = { icon = icons.text, color = 'blue' } },
      { '<leader>Y', desc = 'Copy to end of line to system clipboard', icon = { icon = icons.text, color = 'blue' } },
      { '<leader>y', desc = 'Copy to system clipboard', icon = { icon = icons.text, color = 'blue' } },
      { '<leader>q', desc = 'Quit', icon = { icon = icons.file, color = 'red' } },
      { '<leader>w', desc = 'Write', icon = { icon = icons.file, color = 'red' } },

      { '<leader><tab>', desc = 'Goto last buffer', icon = { icon = icons.file, color = 'yellow' } },
      { '<leader>,', desc = 'Open Buffers', icon = { icon = icons.file, color = 'yellow' } },
      { '<leader><space>', desc = 'Find Files', icon = { icon = icons.file, color = 'yellow' } },

      { '<leader>c', group = 'Code', mode = { 'n', 'x' }, icon = { icon = icons.code, color = 'yellow' } },
      { '<leader>g', group = 'Git', icon = { icon = icons.git, color = 'yellow' } },
      { '<leader>l', group = 'LSP', icon = { icon = icons.code, color = 'yellow' } },
      { '<leader>s', group = 'Search', icon = { icon = icons.search, color = 'yellow' } },
      { '<leader>f', group = 'File', icon = { icon = icons.file, color = 'yellow' } },
      { '<leader>b', group = 'Buffer', icon = { icon = icons.file, color = 'yellow' } },
      { '<leader>t', group = 'Toggle', icon = { icon = icons.file, color = 'yellow' } },
      { '<leader>T', group = 'Test', icon = { icon = icons.test, color = 'yellow' } },
      { '<leader>o', group = 'Obsidian', icon = { icon = icons.note, color = 'yellow' } },
      { '<leader>n', group = 'Noice', icon = { icon = icons.note, color = 'yellow' } },
      { '<leader>x', group = 'Trouble', icon = { icon = icons.diagnostics, color = 'yellow' } },
    },
  },
}
